badges:
  - name: "Preview"
    image: "https://img.shields.io/badge/preview-available-blue"
    link: "https://preview.example.com"
    condition: "preview_available == true"
  - name: "Large PR"
    image: "https://img.shields.io/badge/size-large-red"
    condition: "size > 1000"
