badges:
  - name: "Preview"
    image: "https://img.shields.io/badge/preview-available-blue"
    link: "https://preview.example.com"
    condition: "true"
  - name: "Redmine"
    image: "https://img.shields.io/badge/size-small-yellow"
    condition: "true"
  - name: "Size - Large"
    image: "https://img.shields.io/badge/size-large-red"
    condition: "size > 1000"
  - name: "Size - Small"
    image: "https://img.shields.io/badge/size-small-blue"
    condition: "size < 1000"
  - name: "Test"
    image: "https://img.shields.io/badge/size-small-yellow"
    condition: "true"
